### ISSUE TITLE
Организации

### ISSUE THREAD

**Issue by HaykDarbinyan** [GravitinoUp/frontend#101]
Флоу:
1. Перешел на вкладку Организации, создал организацию 

ОР:
Организация появилась в списке

ФР:
Организация не появилась в списке

Примечание:
После того как, отредактировал Тип организации, Номер регистрации, также выдает ошибку

![Image](https://github.com/GravitinoUp/frontend/assets/161712150/dd385bea-0543-45a0-95f3-dc4756bd1966)

**Comment by OgArustamian** [comment]
Данная форма создания/редактирования организации была удалена в прикрепленном ПРе. Данные манипуляии теперь проводятся на странице `/users`
