### ISSUE TITLE
Пользователи. При регистрации Работника отсутствует Подразделение

### ISSUE THREAD

**Issue by HaykDarbinyan** [GravitinoUp/frontend#111]
![Image](https://github.com/GravitinoUp/frontend/assets/161712150/76e80ab4-c5c5-4a41-9609-37310a5f3ee0)
![Image](https://github.com/GravitinoUp/frontend/assets/161712150/5d6c08ad-dc64-412b-ab94-a85a67c7e74f)

Флоу:
1. Перешёл на вкладку Пользователи, создал пользователя.
2. Выбрал тип пользователя - Работник

ОР:
появилась графа Подразделение при регистрации

ФР:
Нет графы Подразделение

**Comment by OgArustamian** [comment]
Не уверен, что баг актуальный.
бэкенд ожидает такой body:
{
  "last_name": "string",
  "first_name": "string",
  "patronymic": "string",
  "phone": "string",
  "role_id": 1,
  "group_id": 1,
  "email": "string",
  "password": "string",
  "property_values": []
}

Не нахожу похожего поля. Может требуется актуализировать макет?

**Comment by OgArustamian** [comment]
подразделение добавлено в форме в прикрепленном ПРе
