### ISSUE TITLE
Пользователи. При регистрации Подрядчика отсутствует Объект обслуживания и неправильный нейминг

### ISSUE THREAD

**Issue by HaykDarbinyan** [GravitinoUp/frontend#112]
Флоу:
1. Перешёл на вкладку Пользователи, создал пользователя.
2. Выбрал тип пользователя - Подрядчик

ОР:
Появилась графа Объект обслуживания

ФР:
Отсутствует графа Объект обслуживания

Примечание:
Ещё неправильный нейминг. У нас написано Тип организации, а в Фигме - Профиль организации
скрины вставил с фигмы

![Image](https://github.com/GravitinoUp/frontend/assets/161712150/712e35d0-d9e2-4c59-a3ae-59db62745b39)
![Image](https://github.com/GravitinoUp/frontend/assets/161712150/3a2e1049-0b93-4213-9250-fcee683ae1ff)
![Image](https://github.com/GravitinoUp/frontend/assets/161712150/86c27619-28f0-4bff-a33d-5637d9394f7b)

**Comment by BasanMuchkaev** [comment]
1. Добавить в метод создания пользователя подрядчика выбор ОО
