### ISSUE TITLE
Филиалы. Отсутствует колонка Номер

### ISSUE THREAD

**Issue by HaykDarbinyan** [GravitinoUp/frontend#114]
Флоу:
Перешёл на вкладку Филиалы

ОР:
Колонка Номер перед колонкой Название

ФР:
Колонки Номер нет

![Image](https://github.com/GravitinoUp/frontend/assets/161712150/f43a5df2-d9cc-4ebf-8ed4-c2812c9550bc)
![Image](https://github.com/GravitinoUp/frontend/assets/161712150/eeb07a19-14af-4f81-ae5b-35e2e8feceef)

**Comment by OgArustamian** [comment]
Добавил колонку в прикрепленном ПРе
