### ISSUE TITLE
Управление характеристиками. Не получилось создать характеристику

### ISSUE THREAD

**Issue by HaykDarbinyan** [GravitinoUp/frontend#119]
![Image](https://github.com/GravitinoUp/frontend/assets/161712150/63bed756-e096-4e43-944a-84873dc518cd)

Флоу:
Перешёл на вкладку Управление характеристиками, далее создание характеристики

ОР:
Создалась характеристика

ФР:
Характеристика не создалась

**Comment by BasanMuchkaev** [comment]
Изменить текст при валидации
