### ISSUE TITLE
Отчеты. Нет списка подрядчиков и нет колонки Объектов обслуживания

### ISSUE THREAD

**Issue by HaykDarbinyan** [GravitinoUp/frontend#241]
Флоу:
1. Перешел на вкладку Отчеты
2. Перешел на вкладку Уральский филиал
3. Провалился в АПП МАРИИНСКИЙ

ОР:
Появился список подрядчиков
Есть колонка Объект Обслуживания

ФР:
Нет списка подрядчиков
Нет колонки Объект Обслуживания

![Image](https://github.com/GravitinoUp/frontend/assets/161712150/b81d325d-ba68-46d7-a383-048ad4f5b90e)
![Image](https://github.com/GravitinoUp/frontend/assets/161712150/ff257298-b4ce-4231-886a-2069b623234b)

![Image](https://github.com/GravitinoUp/frontend/assets/161712150/e8c3f0ff-7ee1-4b1a-ab27-3676a7b45108)

**Comment by OgArustamian** [comment]
название выводилось и раньше. В прикрепленном ПРе добавил колонку "Объект обслуживания"
