### ISSUE TITLE
QR-cod. Сделать возможность генерации и распечатки QR кодов

### ISSUE THREAD

**Issue by HaykDarbinyan** [GravitinoUp/frontend#247]

**Comment by BasanMuchkaev** [comment]
1. Изменить query параметры в url формы обратной связи с facility на checkpoint
2. Необходимо реализовать генерацию формы с qr-кодом в pdf, которая должна вести на соответствующий url, где в query зашито gravitino.ru/feedback?checkpoint=id
3. Положить в s3 файлы с pdf у которых в key, зашито checkpoint_id, для того, чтобы в личном кабинете у каждого гл. инженера лежал свой qr-код (будет по jwt определять)
4. Реализовать во вкладке администрирование функционал скачивания qr-кодов (на на макте, который Айк переделает)
