### ISSUE TITLE
Список задач. Подборка фильтров, некорректно отображаются задачи по статусам

### ISSUE THREAD

**Issue by HaykDarbinyan** [GravitinoUp/frontend#262]
Флоу:
Перешел на вкладку Список задач
Перешел на вкладку Подобрать фильтры
Выбрал Уральский филиал
Выделили все статусы задач кроме НАЗНАЧЕНА

ОР:
Отображаются все статусы задач кроме назначена

ФР:
Отображаются все статусы, включая НАЗНАЧЕНА

Примечание:
Выделил только 1 статус (Создана), отображаются СОЗДАНА и НАЗНАЧЕНА
Если в фильтрах ни один статус не выделять, он отображает только НАЗНАЧЕНА

![Image](https://github.com/GravitinoUp/frontend/assets/161712150/95241b43-4bd6-47ca-b9f6-4a240b12a88e)
![Image](https://github.com/GravitinoUp/frontend/assets/161712150/d7f4fc80-6cd0-4a6b-82d5-870dd8b11f2c)

**Comment by BasanMuchkaev** [comment]
Проверить фильтры по филиалам
