### ISSUE TITLE
Список задач. При создании задачи не могу выбрать Исполнителя

### ISSUE THREAD

**Issue by HaykDarbinyan** [GravitinoUp/frontend#273]
Флоу:
Перешел на вкладку Список задач
Создал задачу

ОР:
Отображаются Исполнители

ФР:
Не отображаются исполнители

![Image](https://github.com/GravitinoUp/frontend/assets/161712150/3ca956b8-cbe0-4aac-a8dc-c479d3728a49)
![Image](https://github.com/GravitinoUp/frontend/assets/161712150/e5897775-7548-4480-b36a-a15b7fd013f3)

**Comment by OgArustamian** [comment]
Тут проблема в том, что база не заполнена до конца, к выбранным на скринах ПП не привязаны исполнители, поэтому в запросе `organization/all-by-checkpoint` вернулся пустой массив [] без данных об организациях.
