### ISSUE TITLE
Список задач. Сбрасывается на статус ВСЕ с НАЗНАЧЕНА, после смены статуса задачи.

### ISSUE THREAD

**Issue by HaykDarbinyan** [GravitinoUp/frontend#302]
Флоу:
Перешел на вкладку Список задач
Выбрал статус Назначена
Поменял статус задачи

ОР:
Остаюсь на странице со статусом НАЗНАЧЕНА

ФР:
Сбрасывается на ВСЕ задачи

![Image](https://github.com/GravitinoUp/frontend/assets/161712150/c6ae0cbd-59f9-4865-8228-b7654e04a44b)

![Image](https://github.com/GravitinoUp/frontend/assets/161712150/70159ed4-aa94-4ae5-a801-8e5419f4441f)

**Comment by OgArustamian** [comment]
@HaykDarbinyan не получается воспроизвести, покажи видео или на дейли
