### ISSUE TITLE
QR-код нужен подрядчику? Зашёл как Подрядчик (user5@mail.com, ИП Иванов)

### ISSUE THREAD

**Issue by HaykDarbinyan** [GravitinoUp/frontend#347]
![Image](https://github.com/GravitinoUp/frontend/assets/161712150/0e75f6ca-9b91-4718-9c54-894a039e69f6)

**Comment by BasanMuchkaev** [comment]
нет, не нужен

**Comment by BasanMuchkaev** [comment]
надо убрать таб для роли "подрядчик"
