### ISSUE TITLE
Планшет. При просмотре не видна пагинация

### ISSUE THREAD

**Issue by HaykDarbinyan** [GravitinoUp/frontend#354]
https://github.com/GravitinoUp/frontend/assets/161712150/7cca688e-61f8-42d3-a5f7-4566b9829b0f

Флоу:
Зашел в режиме планшета (Масштаб по умолчанию 75%)
Перешел на вкладку Список задач
Пролистываю вниз, всё отображается.
Поменял масштаб на 100% и пролистал вниз

ОР:
Отображается нижняя часть страницы
ФР:
Не отображается нижняя часть страницы

**Comment by OgArustamian** [comment]
У меня не воспроизводится. Мне кажется тут какой-то баг гугл хрома

**Comment by BasanMuchkaev** [comment]
ждем планшет
