### ISSUE TITLE
Доработать метод создания плановых задач

### ISSUE THREAD

**Issue by sangasgar** [GravitinoUp/frontend#38]
Сделать возможность выбора объекта обслуживания при создании задачи

т. е. пользователь может создать задачи на все филилы именно на объект обслуживания (например на все  Котельные)

**Comment by sangasgar** [comment]
Добавить во входные параметра "тип объекта обсулуживания"

**Comment by DevTriangle** [comment]
https://github.com/GravitinoUp/backend/pull/10
