### ISSUE TITLE
Доработать создание плановых задач

### ISSUE THREAD

**Issue by sangasgar** [GravitinoUp/frontend#41]
После выполнения задачи №38
Детали уточнить у Альберта

**Comment by BasanMuchkaev** [comment]
![Image](https://github.com/GravitinoUp/frontend/assets/105434088/31b8cfd2-eb83-4244-aa8d-a7a111a48a59)

1.так не должно быть, если мы выбрали всем филиалам и нажали создать, у нас создаются задачи абсолютно на всех подрядчиков
2. У нас должна быть возможность выбрать филиалы и объекты обслуживания (например мы хотим создать задачи абсолютно на пункты пропуска и только на КПП)
